#!/usr/bin/env ruby

require "bundler/setup"
require "cloudera-manager-client"
require "irb"
url = ENV['CLOUDERA_MANAGER_URI'] || "http://hadoop.com:7111"
username = ENV['CLOUDERA_MANAGER_USER'] || "admin"
password = ENV['CLOUDERA_MANAGER_PASSWORD'] || "password"
ClouderaManager.setup url: url, username: username, password: password
IRB.start
